on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  workflow_run:
    types: [completed]
    workflows: ["conan"]
    branches-ignore: ["main"]
  check_suite:
    types: [completed]
  schedule:
    - cron: "0,15,30,45 * * * *"

name: "auto merge"

jobs:
  automerge:
    name: Auto Merge Pull Requests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install PyGithub
        run: |
          pip install PyGithub
      - name: Auto Merge Pull Request
        run: |
          python .github/workflows/auto-merge.py
        env:
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
